config/routes.rb
Rails.application.routes.draw do
  get 'archives/index'
  resources :entries
  root to: "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord

  validates :calories, :proteins, :carbohydrates, :fats, :meal_type, presence: true

  def day
    self.created_at.strftime("%b %e, %Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where("created_at >= ?", Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered">
  <div class="column is-half">
    <% @entries.each do |day, entries| %>
      <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered mt-6">Entries for <%= day %></h3>

      <nav class="level is-mobile">
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Calories</p>
            <p class="title"><%= entries.pluck(:calories).sum %></p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Proteins</p>
            <p class="title"><%= entries.pluck(:proteins).sum %>g</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Carbohydrates</p>
            <p class="title"><%= entries.pluck(:carbohydrates).sum %>g</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Fats</p>
            <p class="title"><%= entries.pluck(:fats).sum %>g</p>
          </div>
        </div>
      </nav>

      <% entries.each do |entry| %>
        <%= link_to entry_path(entry) do %>
          <div class="card">
            <div class="card-content">
              <strong><%= entry.meal_type %></strong><br/>
              <%= entry.calories %> calories,
              <%= entry.proteins %>g proteins,
              <%= entry.carbohydrates %>g carbs,
              <%= entry.fats %>g fats

            </div>
          </div>


        <% end %>

      <% end %>
    <% end %>
  
  </div>

</div>

<div class="columns is-centered mt-6">
  <%= link_to 'View today Entries', entries_path, class: "button is-info is-outlined is-centered" %>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>

      <div class="message-body">
        <ul>
          <% entry.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :proteins, class: "label" %>
    <%= form.number_field :proteins, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class: "label" %>
    <%= form.number_field :carbohydrates, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :fats, class: "label" %>
    <%= form.number_field :fats, class: "input" %>
  </div>

  <div class="actions columns is-vcentered">
    <%= form.submit class:"button is-success column is-narrow m-3 pt-2" %>
  
    <div class="column"></div>
    <%= link_to 'Cancel', entries_path, class:"column is-narrow has-text-right" %>

  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
<div class="column is-one-third">

  <h1 class="is-size-2 has-text-weight-bold mb-3">Editing Entry</h1>

  <%= render 'form', entry: @entry %>

</div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodcounter &ndash; <%= DateTime.now.to_s(:nice_date) %>
<% end %>

<div class="columns is-centered mt-6">
  <nav class="level is-mobile column is-half">
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Calories</p>
        <p class="title"><%= @entries.pluck(:calories).sum %></p>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Proteins</p>
        <p class="title"><%= @entries.pluck(:proteins).sum %>g</p>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Carbohydrates</p>
        <p class="title"><%= @entries.pluck(:carbohydrates).sum %>g</p>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Fats</p>
        <p class="title"><%= @entries.pluck(:fats).sum %>g</p>
      </div>
    </div>
  </nav>
</div>

<div class="columns mt-1 is-centered">

  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title"><%= entry.meal_type %></p>
        </header>
        <div class="card-content">
          <div class="content">
            <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories</p>
            <p><span class="has-text-weight-bold"><%= entry.proteins %></span> g of proteins</p>
            <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> g of carbohydrates</p>
            <p><span class="has-text-weight-bold"><%= entry.fats %></span> g of fats</p>
            <p class="italic">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
          </div>
        </div>

        <div class="card-footer">
          <%= link_to 'Show' , entry, class: "card-footer-item" %>
          <%= link_to 'Edit' , edit_entry_path(entry), class: "card-footer-item" %>
          <%= link_to 'Delete' , entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item" %>
        </div>
      </div>
    </div>
    <% end %>
</div>

<div class="columns is-centered mt-6">
  <%= link_to 'View all Entries', archives_index_path, class: "button is-info is-outlined is-centered" %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
<div class="column is-one-third">

  <h1 class="is-size-2 has-text-weight-bold mb-3">New Entry</h1>

  <%= render 'form', entry: @entry %>

</div>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <%= @entry.meal_type %> &ndash; <%= DateTime.now.to_s(:nice_date) %>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <nav class="panel is-info">
    <p class="panel-heading">
      <%= @entry.meal_type %>
    </p>

    <div class="panel-block">
      Calories:
      <%= @entry.calories %>
    </div>

    <div class="panel-block">
      Proteins:
      <%= @entry.proteins %>
    </div>

    <div class="panel-block">
      Carbohydrates:
      <%= @entry.carbohydrates %>
    </div>

    <div class="panel-block">
      Fats:
      <%= @entry.fats %>
    </div>
    
    </nav>

    <div class="columns is-mobile">
      <div class="column is-narrow">
        <%= link_to 'Edit', edit_entry_path(@entry), class: "button is-gray" %>
      </div>
      <div class="column"></div>
      <div class="column is-narrow">
        <%= link_to 'Delete', entry_path(@entry), method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger" %>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Foodlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">

  <%= stylesheet_link_tag 'application' , media: 'all' , 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application' , 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render "shared/header" %>

  <% if notice.present? %>
    <div class="notification is-link is-light"><%= notice %></div>
  <% end %>

  <% if alert.present? %>
    <div class="notification is-danger is-light"><%= alert %></div>
  <% end %>


  <div class="container">
    <%= yield %>
  </div>
</body>

</html>

app/views/shared/_header.html.erb
<section class="hero is-info is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
            <%= link_to root_path, class: "navbar-item" do %>
              <span class="has-text-weight-bold is-size-5 pl-2 pr-2 columns is-vcentered">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="26" height="26"><path fill="none" d="M0 0h24v24H0z"/><path fill="#fff" d="M17.5 2a4.5 4.5 0 0 1 2.951 7.897c.355.967.549 2.013.549 3.103A9 9 0 1 1 3.55 9.897a4.5 4.5 0 1 1 6.791-5.744 9.05 9.05 0 0 1 3.32 0A4.494 4.494 0 0 1 17.5 2zm0 2c-.823 0-1.575.4-2.038 1.052l-.095.144-.718 1.176-1.355-.253a7.05 7.05 0 0 0-2.267-.052l-.316.052-1.356.255-.72-1.176A2.5 2.5 0 1 0 4.73 8.265l.131.123 1.041.904-.475 1.295A7 7 0 1 0 19 13c0-.716-.107-1.416-.314-2.083l-.112-.33-.475-1.295 1.04-.904A2.5 2.5 0 0 0 17.5 4zM10 13a2 2 0 1 0 4 0h2a4 4 0 1 1-8 0h2z"/></svg>
                Foodcounter
              </span>
            <% end %>
          </a>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
              <%= link_to "Create new Entry", new_entry_path, class: "button is-success" %>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        <% if content_for(:title) %>
        <%= yield :title %>
        <% else %>
          Foodcounter
        <% end %>
      </p>
    </div>
  </div>

</section>